print("Wassup Buddy!! v10")
print("This message is from 25 SEP")
print("This message is from 25 SEP - update 1")
print("This message is from 25 SEP - update 2")
print("This message is from 25 SEP - removing bracket in the front")
